---
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: springapp-git-application
  namespace: cfmr-cluster
  labels:
    mcmapp: springapp-sample
spec:
  componentKinds:
    - group: app.ibm.com
      kind: Subscription
  descriptor: {}
  selector:
    matchLabels:
      mcmapp: springapp-sample